version: "3.7"
services:
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
      args:
        buildno: 1
    image: 'covid19_dashboard'
    container_name: 'covid19_dashboard'
    volumes:
        - './dashboard:/app/dashboard'
    ports:
        - '8050:8050'
    networks:
        - 'dashboard'

volumes:
  dashboard:

networks:
  dashboard:
    external: True